language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - composer self-update
  - mysql -e 'create database homestead_test;'


script:
  - php artisan key:generate
  - vendor/bin/phpunit